version: "1"
services:
  web:
    image: cinema_base:latest
    container_name: web
    depends_on:
      - database
    command:
      - java -jar /usr/local/lib/cinema_base.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456789
      SPRING_JPA_HIBERNATE_DDL-AUTO: none
      SPRING_LIQUIBASE_ENABLED: true
      HOSTNAME: 91.241.64.80
    ports:
      - "5557:5557"
  database:
    restart: always
    image: postgres:14-alpine
    container_name: database
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456789"
    ports:
      - "5432:5432"
