version: "1"
services:
  web:
    image: cinema_base:latest
    container_name: web
    depends_on:
      - database
    command:
      - java -Dspring.profiles.active=dev -jar /usr/local/lib/cinema_base.jar
    environment:
      HOSTNAME: 91.241.64.80
    ports:
      - "5557:5557"
  database:
    restart: always
    image: postgres:14-alpine
    container_name: database
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456789"
    ports:
      - "5432:5432"
